# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Book Title')),
                ('author', models.CharField(max_length=200, verbose_name='Author')),
                ('publisher', models.CharField(max_length=200, verbose_name='Publisher')),
                ('copyright_date', models.DateField(verbose_name='Copyright Date')),
                ('description', models.TextField()),
                ('isbn', models.IntegerField(verbose_name='ISBN')),
                ('publication_date', models.DateField(verbose_name='Publication Date')),
                ('series', models.CharField(max_length=200, verbose_name='Series Name')),
                ('pages', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('dvd_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Book Title')),
                ('actors', models.CharField(blank=True, max_length=200, null=True, verbose_name='Actores')),
                ('run_time', models.CharField(blank=True, max_length=200, null=True, verbose_name='Run Time')),
                ('raiting', models.CharField(max_length=10, verbose_name='Raiting')),
                ('release_date', models.DateField(verbose_name='Publication Date')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100, verbose_name='Type Name')),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employee_number', models.IntegerField(verbose_name='Employee Number')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('role', models.CharField(max_length=100, verbose_name='Employee Role')),
                ('email', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='capstone.InventoryType'),
        ),
        migrations.AddField(
            model_name='dvd',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='capstone.Inventory'),
        ),
        migrations.AddField(
            model_name='books',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='capstone.Inventory'),
        ),
    ]
