# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-26 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='Inventory',
            new_name='InventoryItem',
        ),
    ]
