# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-26 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_auto_20171126_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='capstone.InventoryItem'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(blank=True, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Series Name'),
        ),
    ]
