# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_auto_20171126_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.5, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='title',
            field=models.CharField(max_length=200, verbose_name='DVD Title'),
        ),
    ]
