# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_auto_20171127_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
