# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_inventoryitem_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='inventory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='capstone.InventoryItem'),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='inventory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='capstone.InventoryItem'),
        ),
    ]
