# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_auto_20171127_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvd',
            name='raiting',
        ),
        migrations.AddField(
            model_name='dvd',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
