# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_auto_20171127_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='actors',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Actors'),
        ),
    ]
