# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-30 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_dvd_raiting'),
    ]

    operations = [
        migrations.AddField(
            model_name='personentry',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
