# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-30 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0010_personentry_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personentry',
            name='employee_number',
            field=models.CharField(max_length=9, verbose_name='Employee Number'),
        ),
    ]
